// src/app/report/report.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { ActivatedRoute, Params } from '@angular/router';

import {
  Observable,
  empty as observableEmpty,
  combineLatest as observableCombineLatest,
  throwError as observableThrowError,
  Subscription,
} from 'rxjs';
import {
  map,
  switchMap,
  catchError,
  distinctUntilChanged
} from 'rxjs/operators';

import { ServerResponse } from 'bungie-api-ts/user';
import {
  DestinyProfileResponse,
  DestinyCharacterComponent,
  DestinyActivityHistoryResults,
  DestinyPostGameCarnageReportData,
  DestinyPostGameCarnageReportEntry,
  DestinyHistoricalStatsPeriodGroup,
} from 'bungie-api-ts/destiny2';

import { BungieHttpService } from '../services/bungie-http.service';
import { Occurence } from '../models/occurence';

@Component({
  selector: 'app-report',
  templateUrl: './report.component.html',
  styleUrls: ['./report.component.scss']
})
export class ReportComponent implements OnInit, OnDestroy {

  public loadings: { loading: boolean }[];

  private subs: Subscription[];

  private membershipType: Observable<string>;
  private membershipId: Observable<string>;

  private accountResponse: Observable<ServerResponse<DestinyProfileResponse>>;

  public displayName: Observable<string>;
  public characters: Observable<DestinyCharacterComponent[]>;
  public minutesPlayedTotal: Observable<number>;

  public activities: DestinyHistoricalStatsPeriodGroup[];
  public occurences: Occurence[];

  constructor(
    private route: ActivatedRoute,
    private bHttp: BungieHttpService
  ) { }

  ngOnInit() {
    this.loadings = [];
    this.subs = [];
    this.activities = [];
    this.occurences = [];

    this.membershipType = this.route.params
      .pipe(
        map((params: Params) => {
          return params['membershipType'];
        })
      );

    this.membershipId = this.route.params
      .pipe(
        map((params: Params) => {
          return params['membershipId'];
        })
      );

    this.accountResponse = observableCombineLatest(
      this.membershipType,
      this.membershipId
    )
      .pipe(
        map(([membershipType, membershipId]) => {
          try {
            if (membershipType && membershipId) {
              if (membershipType && membershipId) {
                return this.bHttp.bungiePlatformEndpoint + 'Destiny2/' + membershipType + '/Profile/' + membershipId + '/?components=100,200';
              } else {
                return '';
              }
            }
          } catch (e) {
            return '';
          }
        }),
        distinctUntilChanged(),
        switchMap(url => {
          if (url.length) {
            return this.bHttp
              .get(url)
              .pipe(
                catchError((error: any) =>
                  observableThrowError(error.json().error || 'Server error')
                )
              );
          } else {
            return observableEmpty();
          }
        })
      );

    this.displayName = this.accountResponse
      .pipe(
        map(res => {
          return res.Response.profile.data.userInfo.displayName;
        })
      );

    this.characters = this.accountResponse
      .pipe(
        map(res => {
          const characters = [];
          try {
            Object.keys(res.Response.characters.data).forEach(key => {
              characters.push(res.Response.characters.data[key]);
            });
          } catch (e) { }
          return characters;
        })
      );

    this.minutesPlayedTotal = this.characters
      .pipe(
        map(characters => {
          let minutesPlayed = 0;
          characters.forEach(character => {
            minutesPlayed += +character.minutesPlayedTotal;
          });
          return minutesPlayed;
        })
      );

    this.subs.push(
      observableCombineLatest(
        this.membershipId,
        this.membershipType,
        this.characters
      )
        .pipe(
          distinctUntilChanged()
        )
        .subscribe(([membershipId, membershipType, characters]) => {
          characters.forEach(character => {
            const url = this.bHttp.bungiePlatformEndpoint + 'Destiny2/' + membershipType + '/Account/' + membershipId + '/Character/' + character.characterId + '/Stats/Activities/?mode=5&count=250&page=';
            this.getActivites(url, 0);
            // this.getActivites(url, 1);
            // this.getActivites(url, 2);
          });
        })
    );
  }

  getActivites(url: string, page: number) {
    const loading = { loading: true };
    this.loadings.push(loading);

    this.subs.push(
      this.bHttp
        .get(url + page)
        .subscribe((res: ServerResponse<DestinyActivityHistoryResults>) => {
          if (res.Response.activities) {
            this.getPGCR(res.Response.activities);
            // res.Response.activities.forEach(activity => {
            //   this.activities.push(activity);
            //   this.bHttp
            //     .get(this.bHttp.statsPlatformEndpoint + 'Destiny2/Stats/PostGameCarnageReport/' + activity.activityDetails.instanceId + '/')
            //     .subscribe((res: ServerResponse<DestinyPostGameCarnageReportData>) => {
            //       this.addOccurences(res.Response.entries);
            //     });
            // });
            this.getActivites(url, page + 1);
          } else { }
          loading.loading = false;
        })
    );
  }

  getPGCR(activities: DestinyHistoricalStatsPeriodGroup[]) {
    activities.forEach(activity => {
      this.activities.push(activity);
      this.bHttp
        .get(this.bHttp.statsPlatformEndpoint + 'Destiny2/Stats/PostGameCarnageReport/' + activity.activityDetails.instanceId + '/')
        .subscribe((res: ServerResponse<DestinyPostGameCarnageReportData>) => {
          this.addOccurences(res.Response.entries);
        });
    });
  }

  addOccurences(entries: DestinyPostGameCarnageReportEntry[]) {
    entries.forEach((entry: DestinyPostGameCarnageReportEntry) => {
      let occurence = new Occurence(
        entry.player.destinyUserInfo.membershipId,
        entry.player.destinyUserInfo.displayName
      );

      const found = this.occurences.find((o: Occurence) => {
        if (o.membershipId == occurence.membershipId) {
          o.count++;
          return true;
        }
        return false;
      });

      if (!found) {
        this.occurences.push(occurence);
      }
    });

    this.occurences.sort((a, b) => {
      return a.count > b.count ? -1 : 1;
    });
  }

  ngOnDestroy() {
    this.subs.forEach(sub => sub.unsubscribe());
  }

}

<h2>{{ displayName | async }}</h2>
<p *ngIf="loading">Fteching data... This could take a while.</p>

<div *ngIf="!loading">

  <p>You played a total of {{ minutesPlayedTotal | async }} minutes.</p>

  <h3 *ngIf="pgcr.length">Players encountered</h3>
  <p>
    You encountered a total of {{ occurences.length }} players in PvP over the course of NB games.
    <br>
    Here are the first one hundred of them :
  </p>
  <ul>
    <li *ngFor="let occurence of occurences; let i = index">
      <div *ngIf="i <= 100">
        {{ occurence.displayName }} : {{ occurence.count }} times
      </div>
    </li>
  </ul>

</div>

// src/views/Report/Report.vue
<template>
  <div id="player-report">
    <p v-if="loadingProfile">Loading profile...</p>
    <template v-if="!loadingProfile && profile">
      <div class="flex items-baseline space-x-2">
        <h2 class="text-3xl font-bold">{{ profile.userInfo.displayName }}</h2>
        <span v-if="isLoading" class="text-sm text-light-800">fetching activities...</span>
      </div>

      <div class="flex justify-between text-light-700">
        <p>
          Found {{ encountersState.encounters.length }} players
          <span v-if="wasCanceled">(search canceled)</span>
        </p>
        <X
          v-if="isLoading"
          @click="cancelAll(true)"
          class="cursor-pointer"
          title="Cancel non-cached requests"
        />
      </div>

      <router-view></router-view>
    </template>
  </div>
</template>

<script lang="ts">
import { computed, defineComponent, ref, watch } from 'vue';
import { useRoute } from 'vue-router';

import axios from 'axios';
import { BungieMembershipType, PlatformErrorCodes, ServerResponse } from 'bungie-api-ts/app';
import {
  DestinyActivityHistoryResults,
  DestinyCharacterComponent,
  DestinyPostGameCarnageReportData
} from 'bungie-api-ts/destiny2/interfaces';

import { bhttp, getPGCR } from '@/api';
import EncountersStore from '@/stores/encounters';
import useGetProfile from '@/composables/useGetProfile';
import X from '@/components/icons/X.vue';

export default defineComponent({
  components: {
    X
  },
  setup() {
    // state
    const encountersState = ref(EncountersStore.state);

    // profile fetching
    const { getProfile, profile, characters, loadingProfile, cancelToken } = useGetProfile();

    // Loadings
    class Loading {
      constructor(characterId: string) {
        this.characterId = characterId;
        this.loading = true;
      }

      characterId: string;
      loading: boolean;
    }
    const loadings = ref([] as Loading[]);
    const isLoading = computed(() => {
      if (!characters.value.length) return false;
      else {
        return loadings.value.filter(l => l.loading).length > 0;
      }
    });

    // Get PGCRs
    const onPgcrResult = (pgcr: DestinyPostGameCarnageReportData): void => {
      pgcr.entries.forEach(entry => {
        const player = entry.player;

        if (
          profile.value &&
          player.destinyUserInfo.displayName &&
          entry.player.destinyUserInfo.membershipId !== profile.value.userInfo.membershipId
        ) {
          EncountersStore.addEncounter(pgcr.activityDetails.instanceId, player);
        }
      });
    };

    const getActivities = async (
      character: DestinyCharacterComponent,
      page: number
    ): Promise<void> => {
      const mode = 5;
      const count = 250;

      try {
        const { data } = await bhttp.get(
          `Destiny2/${character.membershipType}/Account/${character.membershipId}/Character/${character.characterId}/Stats/Activities/`,
          {
            cancelToken: cancelToken.value.token,
            params: { count: count, mode: mode, page: page }
          }
        );

        const res: ServerResponse<DestinyActivityHistoryResults> = data;
        if (res.ErrorCode != PlatformErrorCodes.DestinyPrivacyRestriction) {
          if (res.Response.activities && res.Response.activities.length) {
            res.Response.activities.forEach(act => {
              getPGCR(act.activityDetails.instanceId, cancelToken.value.token).then(onPgcrResult);
            });

            getActivities(character, (page += 1));
          } else {
            const loading = loadings.value.find(l => l.characterId === character.characterId);
            if (loading) {
              loading.loading = false;
            }
          }
        }
      } catch (thrown) {
        if (axios.isCancel(thrown)) {
          console.log('activities canceled: ', thrown.message);
        } else {
          console.error(thrown);
        }
      }
    };

    // cancel
    const wasCanceled = ref(false); // todo useCancel
    const cancelAll = (isManualCancel: boolean) => {
      cancelToken.value.cancel('Cancelled by new profile fetch');
      loadings.value.forEach(l => (l.loading = false));
      wasCanceled.value = isManualCancel;
    };

    // route watching
    const route = useRoute();
    watch(
      () => route.params,
      async params => {
        const membershipType = (params['membershipType'] as unknown) as BungieMembershipType;
        const membershipId = params['membershipId'] as string;

        if (
          !profile.value ||
          (profile.value &&
            (profile.value.userInfo.membershipType.toString() !== membershipType.toString() ||
              profile.value.userInfo.membershipId !== membershipId))
        ) {
          if (membershipType && membershipId) {
            cancelAll(false);

            getProfile(membershipType, membershipId, true).then(() => {
              characters.value.forEach(c => {
                loadings.value.push(new Loading(c.characterId));
                getActivities(c, 0);
              });
            });
          }
        }
      },
      { immediate: true }
    );

    return {
      encountersState,

      loadingProfile,
      profile,

      isLoading,

      wasCanceled,
      cancelAll
    };
  }
});
</script>
